"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$netns\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$hostname\
$helm\
$c\
$cpp\
$rust\
$golang\
$gradle\
$nodejs\
$php\
$java\
$julia\
$kotlin\
$lua\
$haskell\
$python\
$docker_context\
$conda\
($cmd_duration$jobs$status)$time\
$line_break\
$shell\
$character"""

palette = 'catppuccin_frappe'

[os]
disabled = false

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = "󰣇 "
Artix = "󰣇 "
EndeavourOS = " "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Pop = " "

# Use when needed :/
#[sudo]
#disabled = false
#format = '[ ]($style)'
#style = "bold red"

[username]
show_always = true
style_user = "bold yellow"
style_root = "bold red"
format = '[$user ]($style)'

[directory]
style = "bold lavender"
truncation_length = 4
truncation_symbol = "…/"
format = '[in $path ]($style)'
read_only = ' '

[directory.substitutions]
"Desktop" = "󰟀 Desktop"
"Documents" = "󰈙 Documents"
"Downloads" = " Downloads"
"Music" = "󰝚 Music"
"Pictures" = " Pictures"
"Videos" = "󰕧 Videos"
"Public" = "󱞊 Public"
"Templates" = "󰅩 Templates"
"Developer" = "󰲋 Developer"
"Projects" = "󰲋 Projects"
"project" = "󰲋 project"
"projects" = "󰲋 projects"
"Code" = "󰲋 Code"
"code" = "󰲋 code"
"Repos" = "󰏖 Repos"
"repos" = "󰏖 repos"
"Repository" = "󰏖 Repository"
"repository" = "󰏖 repository"
"GitHub" = "󰊤 GitHub"
"github" = "󰊤 github"
".config" = " .config"
".local" = "󰒓 .local"
".cache" = "󰪺 .cache"
"dotfiles" = "󱁿 dotfiles"
"src" = "󰴉 src"
"bin" = "󱧼 bin"
"lib" = "󰆼 lib"

[git_branch]
symbol = ""
format = 'on [$symbol $branch(:$remote_branch) ]($style)'
style = "bold green"
ignore_branches = ['master', 'main']

[git_commit]
only_detached = true
style = "dimmed mauve"
tag_disabled = false
format = "[\\($hash$tag\\) ]($style)"

[git_state]
style = "bold red"
format = "[\\($state( $progress_current/$progress_total)\\) ]($style)"

[git_status]
style = "bold maroon"
format = "[\\[$all_status$ahead_behind\\] ]($style)"

[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
disabled = false
format = "\\([+$added]($added_style)/[-$deleted]($deleted_style)\\) "

[fill]
symbol = ' '

[helm]
symbol = " "
style = "bold deep-blue"

[jobs]
symbol = "[ ](blue italic)"

[julia]
symbol = " "

[lua]
symbol = "󰢱 "

# Enable later.
[kubernetes]
disabled = true

[netns]
symbol = "🌐 "
style = "bold yellow"

[hostname]
ssh_only = true
ssh_symbol = "🌏 "
style = "bold teal"
format = '[$ssh_symbol$hostname ]($style)'

[nodejs]
symbol = " "

[c]
symbol = " "
style = "bold deep-blue"

[cpp]
symbol = " "

[rust]
symbol = " "

[golang]
symbol = " "
style = 'bold sky'

[php]
symbol = " "

[java]
symbol = " "
style = "bold peach"

[gradle]
symbol = " "
style = "bold blue"

[kotlin]
symbol = " "

[haskell]
symbol = " "

[python]
symbol = " "

[dotnet]
symbol = "󰪮 "

[docker_context]
symbol = " "

[container]
symbol = " "

[status]
format = '[$symbol $status ]($style)'
disabled = false
style = "bold red"
map_symbol = true

[cmd_duration]
show_milliseconds = true
min_time = 500
format = '[ 󱦟 $duration ]($style)'
style = "fg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[time]
disabled = false
use_12hr = false
time_format = "%a %R"
format = '[ 󰥔 $time ]($style)'
style = "bold flamingo"

[line_break]
disabled = false

[shell]
fish_indicator = '󰈺 '
powershell_indicator = '󰨊 '
bash_indicator = ' '
zsh_indicator = ' '
disabled = false
style = "bold overlay1"
format = '[$indicator ]($style)'

[character]
disabled = false
success_symbol = '[](bold green)'
error_symbol = '[✗](bold mauve)'
vimcmd_symbol = '[](bold green)'
vimcmd_replace_one_symbol = '[](bold purple)'
vimcmd_replace_symbol = '[](bold purple)'
vimcmd_visual_symbol = '[](bold yellow)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
deep-blue = "#1e66f5"
