# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# History
set -g history-limit 50000

# Indexing
set -g base-index 1
setw -g pane-base-index 1

# Terminal
set -g default-terminal "tmux-256color"
set -as terminal-features ,xterm-256color:RGB

# Responsiveness
set -sg escape-time 10

# Reload
bind r source-file "$HOME/.config/tmux/tmux.conf" \; display-message "tmux config reloaded"

# Navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Splits
bind | split-window -h
bind - split-window -v

# Mouse
set -g mouse on

# TPM plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Resurrect
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes 'ssh vim nvim lazygit'

# Continuum
set -g @continuum-save-interval '15'
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
