# ~/.tmux.conf

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Bigger scrollback
set -g history-limit 50000

# Start window/pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Better colors
set -g default-terminal "tmux-256color"
set -as terminal-features ',xterm-256color:RGB'

# Easier config reload
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Vim-like pane movement, but keep default bindings too
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Mouse support, useful but not required
set -g mouse on
